#!/usr/bin/env bash
# Record deployed contract addresses from deployment log into DEPLOYMENTS.md
#
# Usage: ./scripts/record-deployments.sh [testnet|mainnet]
#
# This script reads the deployment log generated by deploy.sh and updates
# DEPLOYMENTS.md with contract addresses, versions, and timestamps.

set -euo pipefail

NETWORK="${1:-testnet}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "${SCRIPT_DIR}")"
DEPLOYMENT_LOG="${REPO_ROOT}/.deployment-log-${NETWORK}.json"
DEPLOYMENTS_FILE="${REPO_ROOT}/DEPLOYMENTS.md"

if [ ! -f "${DEPLOYMENT_LOG}" ]; then
  echo "❌ Error: Deployment log not found at ${DEPLOYMENT_LOG}"
  echo "Run ./scripts/deploy.sh ${NETWORK} first"
  exit 1
fi

echo "Recording deployments from ${DEPLOYMENT_LOG}..."

# Parse deployment log and generate markdown table
TIMESTAMP=$(jq -r '.timestamp' "${DEPLOYMENT_LOG}")
DEPLOYMENTS=$(jq -r '.deployments[] | "| \(.name) | \(.contract_id) | \(.version) | \(.deployed) | — |"' "${DEPLOYMENT_LOG}")

# Determine network section name
NETWORK_SECTION="${NETWORK^} Deployments"  # Capitalize first letter
NETWORK_ANCHOR="$(echo "${NETWORK}" | tr '[:upper:]' '[:lower:]')net"

# Create updated deployments table for this network
NETWORK_TABLE="## ${NETWORK_SECTION}

Contracts deployed to **${NETWORK}** on ${TIMESTAMP}:

| Contract | Address | Version | Deployed | Notes |
|----------|---------|---------|----------|-------|
${DEPLOYMENTS}

**Last Updated**: ${TIMESTAMP}

To verify deployments:
\`\`\`bash
./scripts/verify.sh ${NETWORK}
\`\`\`

For upgrade procedures:
\`\`\`bash
./scripts/upgrade.sh ${NETWORK}
\`\`\`
"

# Read existing DEPLOYMENTS.md and insert/replace the network section
if grep -q "^## ${NETWORK_SECTION}$" "${DEPLOYMENTS_FILE}"; then
  echo "Updating existing ${NETWORK_SECTION}..."
  
  # Find line numbers for the section
  START_LINE=$(grep -n "^## ${NETWORK_SECTION}$" "${DEPLOYMENTS_FILE}" | cut -d: -f1)
  
  # Find the next section or end of file
  END_LINE=$(tail -n +$((START_LINE + 1)) "${DEPLOYMENTS_FILE}" | grep -n "^## " | head -1 | cut -d: -f1)
  
  if [ -z "${END_LINE}" ]; then
    END_LINE=$(wc -l < "${DEPLOYMENTS_FILE}")
  else
    END_LINE=$((START_LINE + END_LINE - 2))
  fi
  
  # Replace the section
  {
    head -n $((START_LINE - 1)) "${DEPLOYMENTS_FILE}"
    echo "${NETWORK_TABLE}"
    tail -n +$((END_LINE + 1)) "${DEPLOYMENTS_FILE}"
  } > "${DEPLOYMENTS_FILE}.tmp"
  
  mv "${DEPLOYMENTS_FILE}.tmp" "${DEPLOYMENTS_FILE}"
else
  echo "Creating new ${NETWORK_SECTION}..."
  
  # Find where to insert (after the header, before Mainnet or end)
  if [ "${NETWORK}" = "testnet" ]; then
    # Insert testnet section after "## Testnet Deployments" placeholder
    sed -i "/^## Testnet Deployments$/,/^## Mainnet Deployments$/{ /^## Mainnet Deployments$/i\\
${NETWORK_TABLE}
" "${DEPLOYMENTS_FILE}" 2>/dev/null || true
  fi
fi

echo "✓ Updated ${DEPLOYMENTS_FILE}"
echo ""
echo "Changes:"
echo "--------"
git diff --no-color "${DEPLOYMENTS_FILE}" 2>/dev/null || true

echo ""
echo "To commit these changes:"
echo "  git add DEPLOYMENTS.md"
echo "  git commit -m 'docs: record ${NETWORK} deployments from ${TIMESTAMP}'"
